"""Initial migration - create all tables

Revision ID: 784d68339dff
Revises: 
Create Date: 2025-09-15 00:29:27.888931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784d68339dff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval_ms_default', sa.Integer(), nullable=False),
    sa.Column('metrics_default_json', sa.Text(), nullable=True),
    sa.Column('windows_default_json', sa.Text(), nullable=True),
    sa.Column('thresholds_json', sa.Text(), nullable=True),
    sa.Column('retention_policy_json', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_preferences_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prefs_json', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index('ix_profiles_default', ['is_default'], unique=False)
        batch_op.create_index('ix_profiles_name', ['name'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index('ix_tags_name', ['name'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at_ms', sa.Integer(), nullable=True),
    sa.Column('ended_at_ms', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('inactive', 'active', 'paused', 'ended')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_created_at', ['created_at_ms'], unique=False)
        batch_op.create_index('ix_sessions_profile', ['profile_id'], unique=False)
        batch_op.create_index('ix_sessions_status', ['status'], unique=False)
        batch_op.create_index('ux_one_active_session', ['status'], unique=True, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))

    op.create_table('runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'concluded', 'failed', 'canceled', 'interrupted')", name='ck_run_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index('ix_runs_session', ['session_id'], unique=False)
        batch_op.create_index('ix_runs_session_time', ['session_id', 'start_ms'], unique=False)
        batch_op.create_index('ix_runs_status', ['status'], unique=False)

    op.create_table('session_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'tag_id', name='ux_session_tag')
    )
    with op.batch_alter_table('session_tags', schema=None) as batch_op:
        batch_op.create_index('ix_session_tags_session', ['session_id'], unique=False)
        batch_op.create_index('ix_session_tags_tag', ['tag_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_run', ['run_id'], unique=False)
        batch_op.create_index('ix_events_session_ts', ['session_id', 'ts_ms'], unique=False)
        batch_op.create_index('ix_events_ts', ['ts_ms'], unique=False)
        batch_op.create_index('ix_events_type', ['event_type'], unique=False)

    op.create_table('run_tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'tag_id', name='ux_run_tag')
    )
    with op.batch_alter_table('run_tags', schema=None) as batch_op:
        batch_op.create_index('ix_run_tags_run', ['run_id'], unique=False)
        batch_op.create_index('ix_run_tags_tag', ['tag_id'], unique=False)

    op.create_table('samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('ts_ms', sa.Integer(), nullable=False),
    sa.Column('metric_group', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.REAL(), nullable=False),
    sa.Column('device_index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index('ix_samples_device', ['device_index'], unique=False)
        batch_op.create_index('ix_samples_mgroup_name', ['metric_group', 'metric_name'], unique=False)
        batch_op.create_index('ix_samples_run_ts', ['run_id', 'ts_ms'], unique=False)
        batch_op.create_index('ix_samples_session_ts', ['session_id', 'ts_ms'], unique=False)
        batch_op.create_index('ix_samples_ts', ['ts_ms'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index('ix_samples_ts')
        batch_op.drop_index('ix_samples_session_ts')
        batch_op.drop_index('ix_samples_run_ts')
        batch_op.drop_index('ix_samples_mgroup_name')
        batch_op.drop_index('ix_samples_device')

    op.drop_table('samples')
    with op.batch_alter_table('run_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_run_tags_tag')
        batch_op.drop_index('ix_run_tags_run')

    op.drop_table('run_tags')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_type')
        batch_op.drop_index('ix_events_ts')
        batch_op.drop_index('ix_events_session_ts')
        batch_op.drop_index('ix_events_run')

    op.drop_table('events')
    with op.batch_alter_table('session_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_session_tags_tag')
        batch_op.drop_index('ix_session_tags_session')

    op.drop_table('session_tags')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_status')
        batch_op.drop_index('ix_runs_session_time')
        batch_op.drop_index('ix_runs_session')

    op.drop_table('runs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ux_one_active_session', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
        batch_op.drop_index('ix_sessions_status')
        batch_op.drop_index('ix_sessions_profile')
        batch_op.drop_index('ix_sessions_created_at')

    op.drop_table('sessions')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index('ix_tags_name')

    op.drop_table('tags')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_profiles_name')
        batch_op.drop_index('ix_profiles_default')

    op.drop_table('profiles')
    op.drop_table('preferences')
    # ### end Alembic commands ###
